### ISSUE TITLE
Crash on Quick Actions menu call

### ISSUE THREAD

**Issue by Cassandra-d** [BADF00D/DisposableFixer#132]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of DisposableFixer: 2.1.3
- [x] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Call Quick actions menu
Actual: exception.
Expected: no exceptions.

### Source Code
```csharp
class Program
{
	static async Task Main(string[] args)
	{
		HttpResponseMessage resp;

		using (var client = new HttpClient())
		{
			using (var stringContent = new StringContent("data"))
			{
				resp = await client.PostAsync("Url", stringContent);
			}
		}
	}
}
```

### Screenshot
![dispose2](https://user-images.githubusercontent.com/2866070/66580203-afdaae00-eb86-11e9-9a08-429aa629347d.gif)

**Comment by BADF00D** [comment]
Thanks for reporting. 

My stacktrace on the bug:
```csharp

System.InvalidOperationException : Sequence contains no matching element
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source,Func`2 predicate)
   at DisposableFixer.Extensions.BlockSyntaxExtension.TryFindLastStatementThatUsesVariableWithName(BlockSyntax block,String variableName,StatementSyntax& lastUsageStatement)
   at async DisposableFixer.CodeFix.DisposeLocalVariableAfterLastUsageCodeFixProvider.Apply(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavor(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavors(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by Cassandra-d** [comment]
@BADF00D 
Thanks for improving your awesome Disposable helper.

Is my stack trace important in reporting issues? It isn't mentioned in template for newly created issues so I wasn't sure is it helpful to add it to issue or will it only take space.

**Comment by BADF00D** [comment]
It was more a kind of note to myself. Within the test I often have to reimplement the api I'm writing test for ( In this case System.Net.Http). Therefor I use the stacktrace in order to check if the bug occures at the same location, after my hacking. But if you have a stacktrace, I'm always glad to get it.
